config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/users/:user_id/links', to: 'links#index'
      put '/users/:user_id/links/:link_id', to: 'links#update'
    end
  end

  resources :users, only: [:new, :create]
  resources :links, only: [:index, :create, :edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
require 'uri'

class Link < ActiveRecord::Base
  belongs_to :user
  validates :url, presence: true,
                  format: { with: URI::regexp(%w(http https)) }
  validates :title, presence: true
end

app/models/link_parser.rb
class LinkParser
  attr_reader :parsed_input

  def initialize(input)
    @parsed_input = input.split(' ')
  end

  def url
    parsed_input[0]
  end

  def command
    parsed_input[1]
  end

  def recipient
    parsed_input[2]
  end

  def should_be_emailed?
    command == '\:cc'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email_address, presence: true, uniqueness: true
  validates :password, presence: true
  validates_confirmation_of :password

  has_many :links
  has_secure_password
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  def index
    render json: Link.where(user: params[:user_id])
  end

  def update
    link = Link.find_by(user: params[:user_id], id: params[:link_id])
    link.update(link_params)
    render json: link
  end

private

  def link_params
    params.require(:link).permit(:title, :url, :read)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = current_user.links
  end

  def create
    parsed_link = LinkParser.new(link_params[:url])
    link = current_user.links.new(url: parsed_link.url , title: link_params[:title])
    if link.save && parsed_link.should_be_emailed?
      UserNotifier.send_link(current_user, parsed_link.recipient, parsed_link.url).deliver_now
      flash[:success] = "Successfully created link and sent email to #{parsed_link.recipient}!"
    elsif link.save
      flash[:success] = "Successfully created link!"
    else
      flash[:error] = 'Invalid link. Please make sure you have a valid URL and enter all parameters.'
    end
    redirect_to links_path
  end

  def edit
    @link = current_user.links.find(params[:id])
  end

  def update
    @link = current_user.links.find(params[:id])
    parsed_link = LinkParser.new(link_params[:url])
    if @link.update(url: parsed_link.url, title: link_params[:title])
      flash[:success] = 'Successfully updated link.'
      redirect_to links_path
    else
      flash.now[:error] = 'Invalid update. Please make sure you have a valid URL and enter all parameters.'
      render :edit
    end
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email_address: params[:session][:email_address])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:danger] = "Invalid login"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You have successfully created a new account."
      redirect_to root_path
    else
      flash.now[:danger] = "Invalid login."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_link_status(link_status)
    if link_status
      '<button class="read-status">Mark as Unread</button>'.html_safe
    else
      '<button class="read-status">Mark as Read</button>'.html_safe
    end
  end
end

app/views/home/show.html.erb
  <% if current_user %>
  <h3>Logged in as <%= current_user.email_address %></h3>
  <h4><%= link_to "My Links", links_path %></h4>
  <h4><%= link_to "Logout", logout_path, method: :delete %></h4>
  <% else %>
  <h4><%= link_to 'Login', login_path %></h4>
  <h4><%= link_to 'Create New Account', new_user_path %></h4>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>URLockbox</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
  <div class='container'>
    <% flash.each do |type, message| %>
    <%= content_tag :div, sanitize(message), class: "alert alert-#{type}" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/links/edit.html.erb
<h1>Edit Link</h1>
<div id="edit-link-form" class="well new-form">
  <%= form_for @link do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: "Title" %>
  <br>
  <%= f.label :url %>
  <%= f.url_field :url, placeholder: "URL" %>
  <br>
  <br>
  <%= f.submit "Save" %>
  <% end %>
</div>

app/views/links/index.html.erb
  <h4><%= link_to 'Logout', logout_path, method: :delete %></h4>

  <h1 class='text-center well'>My Links</h1>

  <div class='row'>
    <div class='col-md-12 text-center'>
      <h4>Submit a New Link:</h4>
      <h6>(Must include http or https in URL)</h6>
      <div id="new-link-form">
        <%= form_for :link do |f| %>
        <%= f.text_field :title, placeholder: "Title" %>
        <%= f.url_field :url, placeholder: "URL" %>
        <%= f.submit "Save" %>
        <% end %>
      </div>
      <br>
      <p>Email a link to a friend! Simply enter your URL in this format: <b>http://example.com \:cc friend@example.com</b></p>
    </div>
  </div>
  <br>

  <div class='row well'>
    <div class='col-md-4 text-center'>
      <h4>Filter By:</h4>
      <div id='filter-by-status'>
        <button id='show-all'>All</button>
        <button id='show-only-read'>Read</button>
        <button id='show-only-unread'>Unread</button>
      </div>
    </div>

    <div class='col-md-4 text-center'>
      <h4>Search Current Links:</h4>
      <form id='search-ideas' class="ui-filterable">
        <input id="linkFilter" data-type="search">
      </form>
    </div>

    <div class='col-md-4 text-center'>
      <h4>Sort in Alphabetical Order:</h4>
      <div id='alphabetic-sort'>
        <button id='alphabetic-sort-button' >Alphabetic Sort</button>
      </div>
    </div>


  </div>

  <br>

  <div id='results'>
    <table id='links-table' class='table table-striped table-bordered table-condensed'>
      <thead>
        <tr>
          <th>Title</th>
          <th>Url</th>
          <th>Read</th>
          <th>Change Status</th>
          <th>Edit Link</th>
        </tr>
      </thead>
      <tbody>
        <% @links.each do |link| %>
        <tr class='link' data-user-id=<%= current_user.id %> data-link-id=<%= link.id %>>
          <td class="link-title"><%= link.title %></td>
          <td class="link-url<%= ' read-link' if link.read %>"><%= link_to link.url, link.url, class: 'link-text' %></td>
          <td class='link-read-status'><%= link.read %></td>
          <td><%= check_link_status(link.read) %></td>
          <td class='edit-link'><p><%= link_to 'Edit', edit_link_path(link) %></p></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/user_notifier/send_link.html.erb
<h3>Hey, <%= @recipient %>!</h3>
<h4><%= @user.email_address %> sent you a link!</h4>

<p>Check out the link at <%= link_to @link, @link %>!</p>

app/views/user_notifier/send_link.text.erb
<h3>Hey, <%= @recipient %>!</h3>
<h4><%= @user.email_address %> sent you a link!</h4>

<p>Check out the link at <%= link_to @link, @link %>!</p>

app/views/users/new.html.erb
<div class="sign-up">
  <h1>Create an Account</h1>
  <br>
  <div class ="sign-up-form well new-form">
    <%= form_for(@user) do |f| %>
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit "Create Account" %>
    <% end %>
    <br>
    Already have an account?
    <%= link_to "Login", login_path %>
  </div>
</div>